### ISSUE TITLE
FrontMatter seems to ignore YAML metadata with array of arrays

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#632]
Got the following front matter truing to get array of arrays of string, two levels. Navigation2 gets completely missed.

```yaml
Navigation1: "1"
Navigation2:
  - 
    - "a/index.md"
    - "a/a/index.md"
  - 
    - "a/b/index.md"
  - 
    - "a/c/index.md"
  -
    - "a/d/index.md"

Navigation3: "2"

```

Later in Razor:
```
 Console.WriteLine("     [+] keys:" + String.Join("\n", document.Keys));
```

Output:
```
Navigation1
Navigation3
```
