### ISSUE TITLE
Incorrect YAML in front matter loosing document

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#636]
I am not sure if this is bug or expected behavior with FrontMatter/Yaml modules.

Pretty simple pipeline - read markdown, read front matter, hit razor and make html.

```cs
Pipelines.Add("markdown",
    ReadFiles("**/*.md"),
    FrontMatter("---", Yaml()).IgnoreDelimiterOnFirstLine(),
    Markdown().UseExtensions().EscapeAt(),
    Razor(),
    WriteFiles(".html")
);
```

Now, the following front matter would lead to a lost document in the Wyam pipeline. 
NOTE! - we happen to put **additional line** at the very beginning of the file...
```yaml
# here should be an empty line!
---
Title: "MyTitle"
Description: ""
---

My content here.
```
That's what Wyam says loosing document between FrontMatter/Yaml -> started with 140 documents ended up with 139. 

```
Executed module ReadFiles in 168 ms resulting in 140 output document(s)
Executing module FrontMatter with 140 input document(s)

# here is one of the document is getting lost - incoming 1, out - 0
# all other documents result in 1 document out
....
Executing module Yaml with 1 input document(s)
                Executed module Yaml in 0 ms resulting in 0 output document(s)
....
Executed module FrontMatter in 128 ms resulting in 139 output document(s)
Executing module Markdown with 139 input document(s)

```
Surely, our fault. Normal looking front matter makes it work:
```yaml
# NO EMPTY LINE HERE
---
Title: "MyTitle"
Description: ""
---
My content
```
This works as well:
```yaml
# NO EMPTY LINE HERE
Title: "MyTitle"
Description: ""
---
My content
```

Wyam works as expected, 140  documents in and 140 out:
```
Executed module ReadFiles in 168 ms resulting in 140 output document(s)
Executing module FrontMatter with 140 input document(s)

# all YAML document processing gets 1 in and 1 out
....
Executing module Yaml with 1 input document(s)
                Executed module Yaml in 0 ms resulting in 1 output document(s)
....
Executed module FrontMatter in 128 ms resulting in 140 output document(s)
Executing module Markdown with 140 input document(s)
```

Verbose logging didn't show the reason on why document was removed from the pipeline. Only count, that's how we found it.

Guess, it's a bit weird behavior because it is expected that YAML module would ADD metadata if found. If nothing if there - just don't enhance the doco, pass and return the original one, right?
