### ISSUE TITLE
deploying w/ GitHub pages on `ubuntu-latest`

### ISSUE THREAD

**Issue by dochoffiday** [statiqdev/Statiq#939]
In the workflow `yml` file, the `runs-on` property needs to be set to `windows-latest`.

I tried using `ubuntu-latest` (which is the default set when creating a new action), but my pages either weren't respecting the `_viewstart` or the `_layout`, because the layout wasn't being applied.

I'm not sure if this is a `bug` or just something that needs to be specified in the [documentation](https://statiq.dev/web/deployment/github-pages).

**Comment by withinfocus** [comment]
Not sure if you still have this issue or not but I just set this Action up personally:

```
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
```

...

```
      - name: .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '5.0.x'
      - run: dotnet run -- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and it works just fine, even with .NET 5. Hope this helps.
